services:
  app_obstetricia:
    build: .
    mem_limit: 512m
    ports:
      - "${APP_PORT}:9090"
    environment:
      DB_URL: jdbc:mysql://obstetricia_segurity:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD_APP}
    restart: always
    depends_on:
      obstetricia_segurity:
        condition: service_healthy

  obstetricia_segurity:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_APP}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD_APP}"]
      timeout: 10s
      retries: 10
