spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto= update
spring.application.name=app_obstetricia
server.port=9090

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE